---
root: true

plugins:
  - babel

env:
  es2021: true
  browser: true

parser: '@babel/eslint-parser'

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
